# Generated by Django 4.1.1 on 2022-09-16 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0003_remove_video_path_video_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='file',
        ),
    ]
